package com.example.jarvisai.data.native

/**
 * Functional callback interface invoked from native C++ code via JNI.
 */
fun interface TokenCallback {
    /**
     * Called whenever a new token piece is generated by llama.cpp.
     * @param token Piece of text generated (UTF-8)
     * @return true to continue generating, false to request immediate abort.
     */
    fun onToken(token: String): Boolean
}
